# Generated by Django 5.1.1 on 2024-09-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='name',
            field=models.CharField(default='hello', max_length=200),
        ),
    ]
